# coding: utf-8

import sys
from setuptools import setup, find_packages

NAME = "ch.inss.jwserver"
VERSION = "1.0.0"

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "connexion>=2.0.2",
    "swagger-ui-bundle>=0.0.2",
    "python_dateutil>=2.6.0"
]

setup(
    name=NAME,
    version=VERSION,
    description="Task, metadata, shell, resources API",
    author_email="john.doe@example.com",
    url="",
    keywords=["OpenAPI", "Task, metadata, shell, resources API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    package_data={'': ['openapi/openapi.yaml']},
    include_package_data=True,
    entry_points={
        'console_scripts': ['ch.inss.jwserver=ch.inss.jwserver.__main__:main']},
    long_description="""\
    OpenAPI specification generated by Joaswizard (https://github.com/networkinss/joaswizard).
    """
)

